### ISSUE TITLE
Withdrawal Functionality

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/payment-contracts#10]
Just checking, is this the withdrawal function, and are there any logs emitted in this case? 

In the case that a user wants to withdraw funds (after depositing)

https://github.com/llamanodes/payment-contracts/blob/main/contracts/Sweeper.vy#L40

**Comment by BlinkyStitt** [comment]
That function is a safety measure. It is used if a user accidentally does an ERC20 transfer of a token (especially a token that is not on the approved deposit list) directly to their payment address. There's nothing we can do to block transfers, so we have this function so that we can take the coins back out.

Withdrawal functionality won't be a part of these contracts. That logic will all be off-chain and will be handled by normal erc20 transfers.
